# See the Readme.md file for more information abou compilation

# Compile the source code and execute it
all: compile run
 
# Compile all c files
compile: main.c sort.c
	gcc main.c sort.c -o main -Wall

# Execute the main file
run: 
	clear && ./main
	
 